### ISSUE TITLE
Properly kill a sail instance?

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#136]
Hello,

I was just using sail, but was not able to find where to close the sail instance (docker container) without killing it via `docker kill (image id)`. Shouldn't this be done when the app window closes?

**Comment by nhooyr** [comment]
You want `sail rm`.

We don't close it when the app window closes in case you're reloading and want to resume with your session intact.

**Comment by roberthmiller** [comment]
Understandable, but... with code-server, you do not know the exact port (a random one is selected). How would you go about reloading?

**Comment by nhooyr** [comment]
`sail ls`

**Comment by roberthmiller** [comment]
Ah, didn't realize that. Thanks.

**Comment by nathanpotter** [comment]
Hey Robert, thanks for trying out Sail!

If you exit out of your app window, you should be able to load a new window with the running environment by calling `sail run <org/repo>`.

If you want a clean and new environment, you can run `sail run --rm <org/repo>` to remove the original container and environment, then launch into a new one.

**Comment by roberthmiller** [comment]
Ah, thanks. I guess I was just too lazy to check the docs... My bad. :eyes:! Thanks!
