### ISSUE TITLE
Anything else I need to know?

### ISSUE THREAD

**Issue by Magistern** [cdr/sail#139]
Seems go was also a prerequisite, and not just git, docker and chrome. After figuring that out, trying to instal sail using your docs, I get:
```
can't load package: package go.coder.com/sail: cannot find package "go.coder.com/sail" in any of:
	/usr/local/go/src/go.coder.com/sail (from $GOROOT)
	/Users/frdo/go/src/go.coder.com/sail (from $GOPATH)
```

**Comment by nathanpotter** [comment]
Hey @Magistern, thanks for trying out Sail and sorry about the missing docs on the installation process. 

I'll open a PR to update the docs with more details about installing with go.

In the meantime, you should be able to install the sail binary through our [releases page](https://github.com/cdr/sail/releases).

So that I can better understand the issue you're facing with the go installation, could you respond with the output of `go env`?

**Comment by stratosgear** [comment]
No the original poster, but I have the same issue as @Magistern and my `go env` shows:

```
 go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/stratos/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/data/projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build906226595=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by nathanpotter** [comment]
Thanks for sending that over, can you try `go get -u go.coder.com/sail` to see if that fixes it? I think the docs are incorrect on the installation. Let me know if that fixes the issue and I'll update the docs accordingly.

If the `go get` still doesn't work because of go mod issues for some reason, you should be able to run:
```
mkdir $HOME/src
cd $HOME/src
git clone https://github.com/cdr/sail.git
cd sail
go install
```

**Comment by Magistern** [comment]
I tried go get -u go.coder.com/sail and it started downloading some stuff, but `sail --help`does nothing
I tried ```
mkdir $HOME/src
cd $HOME/src
git clone https://github.com/cdr/sail.git
cd sail
go install
```
, but `sail --help`does nothing

I did restart terminal between

**Comment by Magistern** [comment]
```
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/frdo/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/frdo/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1s/w4r5xtt95nl3q50r1j4l7pn00000gp/T/go-build738151423=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by stratosgear** [comment]
`go get -u go.coder.com/sail` seemed to execute with no obvious errors/warnings, but there was no sail executable installed anywhere, so that failed.

```
mkdir $HOME/src
cd $HOME/src
git clone https://github.com/cdr/sail.git
cd sail
go install
```
I didn't understand why this had to be installed under my $HOME folder so I tried to do the git clone (and everything that follows) under `/mnt/data/projects/go/src` folder, where I have set my GOPATH folder.  That failed!  Then I tried under `/mnt/data/projects/go/src/github.com/cdr/` and that failed too. 

I was getting:
```
➜ go install
repo.go:10:2: cannot find package "github.com/google/go-github/v24/github" in any of:
        /usr/lib/go/src/github.com/google/go-github/v24/github (from $GOROOT)
        /mnt/data/projects/go/src/github.com/google/go-github/v24/github (from $GOPATH)
project.go:13:2: use of internal package go.coder.com/sail/internal/browserapp not allowed
codeserver.go:18:2: use of internal package go.coder.com/sail/internal/codeserver not allowed
editcmd.go:15:2: use of internal package go.coder.com/sail/internal/dockutil not allowed
editcmd.go:16:2: use of internal package go.coder.com/sail/internal/editor not allowed
hat_builder.go:14:2: use of internal package go.coder.com/sail/internal/hat not allowed
editcmd.go:17:2: use of internal package go.coder.com/sail/internal/randstr not allowed
editcmd.go:18:2: use of internal package go.coder.com/sail/internal/xexec not allowed
```
I never understood how go is doing it's package management, so I stopped trying to be smart about it and tried `$HOME/src`, which DID work, after downloading a ton of dependencies I have NO idea where they went. 

I now have a `sail` under my `/mnt/data/projects/go/bin/`, and `sail --help` properly displays the command line params. 

No time to properly test-drive this now, but after a rough installation process I should be able to start doing so now.  Phew....

**Comment by Magistern** [comment]
how do you get `sail` to be a recognized command in Terminal? There's no info on that. 
I can find sail in my `~/go/bin/` folder and run it using `./sail` but that doesn't help the Chrome browser plugin.

**Comment by stratosgear** [comment]
I see you're on macos and I'm in linux, but I bet your `~/go/bin` is not in your PATH. Maybe that would help with the chrome extension too (I have not tried it yet)

**Comment by Magistern** [comment]
Probably, then perhaps that should go in the installation instructions as well...
How do I do it?

**Comment by stratosgear** [comment]
Well, that is part of the installation instructions when you install go.  Once again, not sure about macos but you should edit some .bashrc file? on your home directory and append the `~/go/bin` to an `export PATH=/some/path;/another/path` definition?

Which brings us back to your original issue, that go is a prerequisite for this tool.

**Comment by nathanpotter** [comment]
Hey @Magistern, you need to have `$GOPATH/bin` added to your `$PATH` as stratosgear mentioned.

Also, go isn't a dependency to sail, only if you want to install it from source and mess with the source code. I'll update the docs again to specify installing that way isn't recommended unless you're actually changing the source.

It's recommended that you install it from the [releases page](https://github.com/cdr/sail/releases) if you just want to use the tool.

**Comment by nathanpotter** [comment]
https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them

**Comment by Magistern** [comment]
Thanks. I guess Sail is for super users :D

**Comment by nathanpotter** [comment]
Lol, sorry for the painful setup experience you had. We've taken a lot of measures in the past day to ensure a more user friendly setup experience. Thanks for submitting the issues and helping us determine where our docs and process were lacking. I hope things are smoother for you now with the more recent updates.

**Comment by Magistern** [comment]
Excellent work on that part. Sail is installed and I can view the manual `sail --help` 
All that remains now is to be able to use it as well. 
trying `sail run cdr/code-server` ends with 
```
Status: Downloaded newer image for codercom/ubuntu-dev-node12:latest
2019-05-22 23:16:42 INFO	writing sail proxy logs to /var/folders/1s/w4r5xtt95nl3q50r1j4l7pn00000gp/T/sailproxy_cdr_code-server865899265
2019-05-22 23:16:53 ERROR	failed to wait for project to be online: context deadline exceeded
+ cd /home/user/code-server
+ sudo chown -R user:user /home/user/.vscode
2019-05-22 23:16:53 ERROR	build run failed: context deadline exceeded
```
and the log file above says:
```
2019-05-22 23:16:42 INFO	listening on http://127.0.0.1:54583
2019-05-22 23:16:53 FATAL	failed to refresh code-server port: failed while trying to find code-server port: Get http://localhost:32773: EOF
```
But perhaps I should put that in a new issue?

**Comment by ammario** [comment]
@nhooyr seems like this might be an issue with the reverse proxy

**Comment by nhooyr** [comment]
Not an issue with the reverse proxy. The container failed to start. If you do a `docker ps -all` then take the id of the container and plop it into `docker logs <id>`, it should show you why.

**Comment by nathanpotter** [comment]
How large is your `~/.vscode/` directory? I wonder if the `chown -R user:user /home/user/.vscode` is taking longer than the 10 second timeout

**Comment by nhooyr** [comment]
We should print out the `docker log` when it fails to start anyway.

**Comment by Magistern** [comment]
> How large is your `~/.vscode/` directory? I wonder if the `chown -R user:user /home/user/.vscode` is taking longer than the 10 second timeout

630M

**Comment by Magistern** [comment]
uninstalled a bunch of extensions now and got a new error:
```
128M/Users/frdo/.vscode/
128M	total
macfrdo: extensions frdo$ sail run cdr/code-server
2019-05-23 08: 31: 28 INFO	using default image codercom/ubuntu-dev-node12: latest
2019-05-23 08: 31: 28 INFO	ensuring image codercom/ubuntu-dev-node12: latest exists
latest: Pulling from codercom/ubuntu-dev-node12
Digest: sha256: 587ef9bdcb39f9edec99034726cd379683646de7f089896257dee97c4f0a0894
Status: Image is up to date for codercom/ubuntu-dev-node12: latest
2019-05-23 08: 31: 30 INFO	writing sail proxy logs to/var/folders/1s/w4r5xtt95nl3q50r1j4l7pn00000gp/T/sailproxy_cdr_code-server320250593
2019-05-23 08: 31: 41 ERROR	failed to wait for project to be online: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
+ cd/home/user/code-server
    +sudo chown-R user: user/home/user/.vscode
2019-05-23 08: 31: 41 ERROR	build run failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by nathanpotter** [comment]
It appears that your docker daemon isn't running. Can you validate by trying to run `docker run hello-world`? See [docker for mac](https://docs.docker.com/docker-for-mac/#explore-the-application)

**Comment by Magistern** [comment]
It says:
```
Hello from Docker!
This message shows that your installation appears to be working correctly.
```

**Comment by roberthmiller** [comment]
Can we repoen this issue as it does not seem to be solved?

**Comment by roberthmiller** [comment]
Also, @Magistern can you try to run sail now? Sometimes, there is a permission problem with the docker daemon upon initial installation. If you have logged out, and back in, the problem could potentially be fixed.

**Comment by Magistern** [comment]
I'll restart the computer and try again then. See you soon.

**Comment by Magistern** [comment]
nah, still the same error:
```
2019-05-23 22:21:13 INFO	using default image codercom/ubuntu-dev-node12:latest
2019-05-23 22:21:13 INFO	ensuring image codercom/ubuntu-dev-node12:latest exists
latest: Pulling from codercom/ubuntu-dev-node12
Digest: sha256:587ef9bdcb39f9edec99034726cd379683646de7f089896257dee97c4f0a0894
Status: Image is up to date for codercom/ubuntu-dev-node12:latest
2019-05-23 22:21:15 INFO	writing sail proxy logs to /var/folders/1s/w4r5xtt95nl3q50r1j4l7pn00000gp/T/sailproxy_cdr_code-server909453300
2019-05-23 22:21:18 INFO	loaded code-server in 3.471843835s
2019-05-23 22:21:29 ERROR	failed to wait for project to be online: context deadline exceeded
+ cd /home/user/code-server
+ sudo chown -R user:user /home/user/.vscode
2019-05-23 22:21:29 ERROR	build run failed: context deadline exceeded
```

**Comment by roberthmiller** [comment]
This is different than the second error that you provided, but the same as the first. Let's see what we can do here... 

Do you have the latest version of sail? If so, can you provide me with `sail version`?

**Comment by Magistern** [comment]
```
$ sail version
Usage: sail [GLOBAL FLAGS] COMMAND [COMMAND FLAGS] [ARGS....]

A utility for managing Docker-based code-server environments.
More info: https://github.com/cdr/sail

[project] can be of form <org>/<repo> for GitHub repos, or the full git clone address.

sail flags:
	--config	Path to config.	(/Users/kojo/.config/sail/sail.toml)
	--install-autocomplete	Install autocomplete	(false)
	--uninstall-autocomplete	Uninstall autocomplete	(false)
	-v	Enable debug logging.	(false)

Commands:
	run	Runs a project container.
	shell	shell drops you into the default shell of a repo container.
	edit	This command allows you to edit your project's environment while it's running.
	ls	Lists all containers with the com.coder.sail label.
	rm	Remove a sail container from the system.
	install-for-chrome-ext	Installs the chrome native message host manifest.
```

**Comment by Magistern** [comment]
is there another way of figuring out?

**Comment by roberthmiller** [comment]
That just means that you are not on the latest version (which provides more detailed error messages).

Can you run this for me:
`curl sail.dev/install.sh | bash`

**Comment by Magistern** [comment]
Then I get this:
```
$ curl sail.dev/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
it didn't update right?

**Comment by Magistern** [comment]
I did this `curl https://sail.dev/install.sh | bash` instead and now...
IT WORKS! Heureka 😄

**Comment by nhooyr** [comment]
@Magistern Glad you worked it out. The reason the first command didn't work is because sail.dev tried to redirect you to https. You should never curl a non HTTPS url and pipe it into bash, always use `https` otherwise you're opening yourself up to a MITM attack.

**Comment by Magistern** [comment]
😳 Oh, thanks for the advice

**Comment by roberthmiller** [comment]
ah, that's true. My bad.

**Comment by Magistern** [comment]
Thank you all for bearing with me. Btw, how do you stop it?

**Comment by roberthmiller** [comment]
Stop the sail instance?
