### ISSUE TITLE
chrome extension: Change the logo?

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#141]
![image](https://user-images.githubusercontent.com/23535075/58129309-7a3d2480-7be7-11e9-87c4-bbaaad823766.png)

This is the current image. 

Is it possible to change it to: 
![image](https://user-images.githubusercontent.com/23535075/58129343-89bc6d80-7be7-11e9-82ef-ba2984e8e84e.png)

Edit:
The second image that I posted is the favicon for sail.dev.

**Comment by nathanpotter** [comment]
@kylecarbs

**Comment by lucacasonato** [comment]
Seems fixed. Close?
