### ISSUE TITLE
default_host in sail.toml doesn't work

### ISSUE THREAD

**Issue by linux-china** [cdr/sail#144]
I changed default_host in sail.toml to internal git host,  then run the sail with following command. 

```
sail run xxx/yyy
```
and Sail reports following error: 

```
2019-05-21 20:15:28 FATAL	failed to clone 'ssh://git@github.com/xxx/yyy'
```

and I find the "github.com" is literal for host absent in  https://github.com/cdr/sail/blob/master/repo.go

```
       // this probably means the host is part of the path
	if r.Host == "" {
		parts := strings.Split(r.trimPath(), "/")
		// we would expect there to be 3 parts if the host is part of the path
		if len(parts) == 3 {
			r.Host = parts[0]
			r.Path = strings.Join(parts[1:], "/")
		} else {
			// as a default case we assume github
			r.Host = "github.com"
		}
	}
```

If host is absent, could we use default_host in sail.toml?

**Comment by nathanpotter** [comment]
Hey @linux-china, thanks for trying out Sail, and for investigating the issue! This should be a pretty quick fix that I'll get pushed out today
