### ISSUE TITLE
install script for linux/darwin

### ISSUE THREAD

**Issue by nhooyr** [cdr/sail#150]
- [ ] ubuntu
- [ ] debian
- [ ] arch
- [ ] macOS (homebrew)
- [ ] centOS
- [ ] fedora
- [ ] alpine

**Comment by nhooyr** [comment]
I can work on the homebrew formula.

**Comment by ammario** [comment]
Would be awesome!

**Comment by nhooyr** [comment]
I also want to mention I really like how yarn documents the installation process:

<img width="1354" alt="Screen Shot 2019-05-22 at 12 02 03 PM" src="https://user-images.githubusercontent.com/10180857/58189927-6fd36700-7c89-11e9-8db0-116fbe8d9d58.png">

Instead of a giant list, you just select your OS and the yarn version you want and you get the information you need.

**Comment by ammario** [comment]
That's very pleasant.

Will require finagling to work with our Hugo docs.

**Comment by ammario** [comment]
I think we should split this into an issue for Homebrew and Ubuntu. The other ones are too niche to be worth our time atm imo.

**Comment by nhooyr** [comment]
Another approach we can take is just to have a install script for now as the above process will take a long time. The install script can be relatively simple, just downloads the binary from github and places it in `/usr/local/bin/sail`, creating `/usr/local/bin` if it does not already exist.

**Comment by ammario** [comment]
I like that... `curl sail.dev/install.sh | bash`
