### ISSUE TITLE
Mutiple open in sail buttons when navigating files on github

### ISSUE THREAD

**Issue by scsmithr** [cdr/sail#157]
![image](https://user-images.githubusercontent.com/4040560/58193280-436b1b00-7c88-11e9-86e6-91b7bdc7e230.png)

1. Go to root of repo on github
2. Go to file or directory in repo
3. Go back, see extra sail button

**Comment by lucacasonato** [comment]
Oops duped by #222. That is fixed by #224 so this can be closed.
