### ISSUE TITLE
Add version flag

### ISSUE THREAD

**Issue by nhooyr** [cdr/sail#163]

**Comment by roberthmiller** [comment]
I will open a PR for this to mimic sshcode's version flag.

**Comment by roberthmiller** [comment]
@nhooyr I am assuming that I should add docs for it, right?

**Comment by nhooyr** [comment]
I don't think docs are necessary. Its an expected feature of all commands.

**Comment by roberthmiller** [comment]
lol ok, I wrote them anyway... should I remove them? :cry:

**Comment by nhooyr** [comment]
lmao, sorry about that. its best the docs remain lean.

**Comment by roberthmiller** [comment]
Ok, no worries. will remove them. I am waiting for my other PR to get approved (I thought that I was only contributing one thing), then I rebase and open a PR for this as it's already done.

**Comment by nhooyr** [comment]
You can just create a new branch and open another PR.

**Comment by roberthmiller** [comment]
I branched off my master, so it contains things for the other PR. I think that would be messy :eyes:
