### ISSUE TITLE
update to workflow/sail_open.sh

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#168]
Not sure what the purpose of that file is... Any ideas?

**Comment by roberthmiller** [comment]
Found it when searching through the docs, but.. I think that the command should change to be `run` instead of `open`

**Comment by nathanpotter** [comment]
Ah good find, that's a relic of the past, I'll update accordingly

**Comment by roberthmiller** [comment]
I already have a PR

**Comment by nathanpotter** [comment]
closed via #170
