### ISSUE TITLE
link gitconfig and ssh to `.sail/Dockerfile` via a share

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#171]
Is this something that we should do via a share just to make working with the repo easier?

Edit:
It is documented here: https://sail.dev/docs/concepts/labels/ as a recommendation, but is this something that we want?

**Comment by ammario** [comment]
Not sure what you mean exactly. 

`.gitconfig` and `.ssh` is already shared into the container by `ubuntu-dev`.

**Comment by roberthmiller** [comment]
Hm, then maybe we should update the docs to note that both of them are auto?

**Comment by roberthmiller** [comment]
Also, I am not sure that you understood what I meant.. 
![image](https://user-images.githubusercontent.com/23535075/58211134-1a16b300-7cb9-11e9-8df4-8be65aaefaed.png)
happens when I try to commit from inside the current sail instance.

**Comment by ammario** [comment]
Ahh, I think the `.gitconfig` share was removed at some point.

I think we can add it here 

https://github.com/cdr/sail/blob/master/images/ubuntu-dev/Dockerfile#L1-L4

Any objections @nathanpotter ?

**Comment by nathanpotter** [comment]
If the `~/.gitconfig` mount source doesn't exist, sail will create it as a directory by default. I think that's why we decided to keep it out of the ubuntu-dev image

**Comment by nathanpotter** [comment]
I know we discussed for a bit with @nhooyr what we should do when a mount source doesn't exist, but I don't think creating the dir makes sense for a scenario like this.

Should we just log an error and not mount it in if it doesn't exist instead of creating it as a dir?

**Comment by roberthmiller** [comment]
how would I go about mounting it without maintaining my own fork?

**Comment by roberthmiller** [comment]
Realized that hats will do this for us.
