### ISSUE TITLE
Should `sail rm` remove the directories as well?

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#174]

**Comment by ammario** [comment]
What directories?

**Comment by roberthmiller** [comment]
The directories that were mounted into the containers

**Comment by roberthmiller** [comment]
to be more specific, sail clones the project when running it. You can edit some code, then push it back to your origin. When you go to remove the sail image, should there be an option to remove the directories that were cloned as well (not do this by default)?

**Comment by coadler** [comment]
I don't think `sail rm` should delete data by default.

I think a good solution might be to add a `--with-data` flag to delete the project data as well.

**Comment by roberthmiller** [comment]
I could create a PR for this if it is something that we actually want to happen.

**Comment by nathanpotter** [comment]
What is the major use case for this? Have you found yourself removing the directory?

**Comment by roberthmiller** [comment]
I have found myself removing the directories (which is why I proposed the PR). 

I am not sure if it should be merged in though, I was just going off of the suggestion that @coadler mentioned.
