### ISSUE TITLE
Rename `--rm` to `--rebuild`

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#182]
I often find myself wanted to change the image in some way, but often times are unable to get to the source (within code-server) to rebuild.

As a current work around, I have to `sail rm org/repo` and then run it again. Do you guys thing that adding a rebuild is worth it?

**Comment by nathanpotter** [comment]
`sail run --rm <org/repo>` should do what you want. It first removes the original container and then builds it fresh

**Comment by roberthmiller** [comment]
Ah, thought that just removed the image after exiting (that would be useful)

**Comment by roberthmiller** [comment]
What are your thoughts on a rename?

**Comment by nathanpotter** [comment]
Yeah I think a rename makes sense
