### ISSUE TITLE
the `~` alias

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#183]
Am having a hard time understanding why `~` is an alias for /home/robert inside the docker image.

Re:
![image](https://user-images.githubusercontent.com/23535075/58270727-7d0b5700-7d58-11e9-8719-c53991c44f7f.png)

Edit: 
The proper alias should be `/home/user`

**Comment by coadler** [comment]
You are probably sharing the `$HOME` env with the container

**Comment by roberthmiller** [comment]
lol, I was.. my bad :cry:
