### ISSUE TITLE
Failed to run "sail run cdr/sshcode"

### ISSUE THREAD

**Issue by yhyddr** [cdr/sail#186]
### errors
![image](https://user-images.githubusercontent.com/32089134/58274176-e6c14a80-7dc4-11e9-807c-894d4a8b6826.png)
## env
macOS with 
curl https://sail.dev/install.sh | bash
sail install-for-chrome-ext
and chrome install with extension
#176  i don't have code-server binary file and i don't download it . It's necessary to download it ?

**Comment by nathanpotter** [comment]
I'll update the release to have that commit

No, sail will automatically download the code-server binary for you

**Comment by nathanpotter** [comment]
I just updated the release, so it should work now if you run `curl https://sail.dev/install.sh | bash`

**Comment by yhyddr** [comment]
fine, It's OK
