### ISSUE TITLE
post build initialization

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#191]
I have found myself every time rebuilding my sail fork and needing to run either:

- go get
- npm install

Is there a way to have a post-build shell script?

**Comment by ammario** [comment]
There's a concept for a `.sail/on_open` file. This is a priority feature for sure.

**Comment by nathanpotter** [comment]
You should be able to add an `ENTRYPOINT` to your hat Dockerfile that can do this

**Comment by roberthmiller** [comment]
That is true. I have not tried this yet.. do you think that an `on_open` would be better than just adding an `ENTRYPOINT`?

**Comment by nathanpotter** [comment]
Not particularly, I think it's probably better to stick with docker idioms when possible

**Comment by roberthmiller** [comment]
Is the entrypoint overwritten by code-server?

**Comment by nathanpotter** [comment]
Ah, I guess I misunderstood how `ENTRYPOINT` worked, yeah having a `.sail/on_open` sounds good to me

**Comment by ammario** [comment]
should be implemented by @nhooyr ... he's most comfortable with the typescript code

**Comment by roberthmiller** [comment]
Would this be a shell script?

**Comment by ammario** [comment]
It would be an executable file

**Comment by roberthmiller** [comment]
I am not understanding this properly then... `.sail/on_open` would be able to run arbitrary code from the user (or repo owner), correct?

**Comment by nhooyr** [comment]
I'm not sure why we need this? Wouldn't you just put this in the project docker file?

**Comment by roberthmiller** [comment]
A start script will not work within the projects Dockerfile because you do not have the files at the time that the image is building. A start script would allow you to have access to the files (package.json, go mod, etc...) allowing you to, on container start, to run `go get` or `npm install`. It is a burden to, every time I start a container (or rebuild it) to do this.

**Comment by roberthmiller** [comment]
Also, does this belong on the `General 1` board?

**Comment by deansheather** [comment]
Maybe this should be a LABEL in the Sail image. Once the container is started, Sail could just read the label from the image and exec the contents of the label in the container.
