### ISSUE TITLE
Allow customization of git clone command

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#195]
I have 2FA on, which requires ssh keys. I have this setup within my sshconfig. Is there any way that we would change this to put a structured string like so: `git clone github:%v` in the `~/.config/sail/sail.toml` file? Of course, the `%v` would be replaced with the repo that is being run.

**Comment by roberthmiller** [comment]
Note: This would also solve #156

**Comment by nathanpotter** [comment]
By default sail clones via ssh, so if you were to run `sail run cdr/sail`, it will expand the clone command to:
`git clone ssh://git@github.com/cdr/sail.git`

**Comment by roberthmiller** [comment]
For me, it needs to be ssh://github:cdr/sshcode

**Comment by roberthmiller** [comment]
of course, I can simply change it but just thought that customization of the command would be good (so I did not have to).

**Comment by roberthmiller** [comment]
I changed it. I still think that it is good for non-github users for example. re: #128

**Comment by coadler** [comment]
This is already configurable via the `default_host` key in the config
