### ISSUE TITLE
chrome extension: failed to run `docker info`

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#201]
I think that we should better display that sail failed to start. Currently, the popup window (black terminal in browser) opens/displays the text/exits without me being able to fully note the error. Not sure that should be the expected behavior. 

Edit:
As a note, on MacOS, this is a problem. On my Linux machine, sail runs beautifully.

**Comment by gedw99** [comment]
great that someone else is having the same issue as me !

i just installed sails and the extension and when i am on a github page it does the exact same thing.
It flashes open a window and dies before i can read anything in that window.
I am on a MAC.

Is there anything i am doing wrong ?

**Comment by joeblew99** [comment]
any answers from the team ?

**Comment by roberthmiller** [comment]
@deansheather @kylecarbs Thoughts?

**Comment by barretlee** [comment]
Same problem, waiting for solution.

**Comment by 13916253446** [comment]
Same problem, waiting for solution.

**Comment by dougnukem** [comment]
Same I'm getting the following error:
```
2020-03-10 17:05:47 FATAL	failed to run `docker info`: exec: "docker": executable file not found in $PATH

failed to read sail output: exit status 1
```

My `docker` is at:
```
$ which docker
/usr/local/bin/docker

$ docker --version
Docker version 19.03.5, build 633a0ea

```

MacOS 10.15.3 (19D76)

**Comment by dougnukem** [comment]
One work around is to launch chrome from the terminal so it has the proper `$PATH`:
```
$ open /Applications/Google\ Chrome.app
```

Then it works fine.

I think the more appropriate fix would be to modify `sail` binary to append `/usr/local/bin` to the `PATH` if it detects it's running on MacOS `darwin` to work around this common setup.

**Comment by dougnukem** [comment]
Proposed fix for `sail` to include `/usr/local/bin` when running on MacOS to work resolve this issue:

https://github.com/cdr/sail/pull/264
