### ISSUE TITLE
github.com/docker/docker redirects to github.com/moby/moby

### ISSUE THREAD

**Issue by yurivict** [cdr/sail#203]

**Comment by deansheather** [comment]
Docker got renamed to Moby a while ago, so this is just a redirect on GitHub's side so old links still go to the right place. Is there a link somewhere that goes `docker/docker` instead of `moby/moby`, or is this affecting `sail` in some way?

**Comment by yurivict** [comment]
You need to rename ```docker/docker``` to ```moby/moby```.

**Comment by deansheather** [comment]
If you're referring to the imports we use in our code, the Moby codebase still uses `docker/docker` so we need to use `docker/docker` in our code as well.

**Comment by yurivict** [comment]
Ok, thanks.
