### ISSUE TITLE
Package is invalid. Details: 'Could not load extension icon 'logo128.png'.'.

### ISSUE THREAD

**Issue by khoomeister** [cdr/sail#208]
Repro:

1. https://chrome.google.com/webstore/detail/sail/deeepphleikpinikcbjplcgojfhkcmna
2. Click "Add to Chrome".
3. This message comes up:

![image](https://user-images.githubusercontent.com/681288/58666222-91ff6180-82e7-11e9-9fad-229995fbca8e.png)

Using Chrome stable - LMK if I can post more debug info!

**Comment by ammario** [comment]
@kylecarbs this can be closed now, right?

**Comment by deansheather** [comment]
The extension on the Chrome Web Store still has this error.

**Comment by zaykl** [comment]
any progress for this issue?

**Comment by kylecarbs** [comment]
Fixed!
