### ISSUE TITLE
Add codercom/ubuntu-dev-llvm8 docker base image

### ISSUE THREAD

**Issue by linux-china** [cdr/sail#212]
LLVM & Clang are very import for some development, for example WebAssembly, Rust etc. It's a little complicated to install LLVM 8 on Ubuntu for junior.  Now we have codercom/ubuntu-dev-gcc8, and could we add codercom/ubuntu-dev-llvm8 on Docker hub.  thanks. 

I have tried some LLVM images from docker hub, but these images not based from  codercom/ubuntu-dev, still some bugs, for example, sudo command not found,  /root/.vscode problem, no "user" account by default.

**Comment by deansheather** [comment]
Created a PR (link above) that contains an llvm-8 image.

**Comment by nathanpotter** [comment]
The image should be pushed up to docker hub now

**Comment by linux-china** [comment]
Great. thanks :)  https://hub.docker.com/r/codercom/ubuntu-dev-llvm8
