### ISSUE TITLE
Unable to install with msys

### ISSUE THREAD

**Issue by Merith-TK** [cdr/sail#239]
I get this issue while installing, using instructions from https://sail.dev/docs/installation/
``build go.coder.com/sail: cannot load go.coder.com/sail/internal/editor: no Go source files``

any idea why?
```env
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ShitNuggit\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:/Miscellaneous/msys/usr/local/gopath
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Miscellaneous\msys\home\ShitNuggit\src\sail\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Miscellaneous\msys\tmp\go-build634270934=/tmp/go-build -gno-record-gcc-switches
```

**Comment by Merith-TK** [comment]
And please do ignore my username.

**Comment by deansheather** [comment]
```
GOHOSTOS=windows
```

Sail only supports Linux and Darwin. If you look in [sail/internal/editor/editor.go](internal/editor/editor.go) you'll notice that it is setup so it only builds on Linux and Darwin.

Please refer to #210 and #151.

**Comment by roberthmiller** [comment]
What is the reason why it only builds on linux and darwin? Is there a specific thing that is blocking it from being built on windows? * beside the derivatives at the top of the file*

**Comment by deansheather** [comment]
Not sure. It's probably because most Linux distros (and Darwin) include vim out of the box. Windows doesn't have vim or any other good editor out of the box.

cc: @ammario

**Comment by roberthmiller** [comment]
Notepad:tm:

**Comment by ammario** [comment]
I don't think there's anything preventing it from being built or ran on Windows. Just need to try and and see what happens.

**Comment by Merith-TK** [comment]
I actually modified the parts the make it freak out, and gives me a random syscall error thing, will post outputs once windows finishes updating.

**Comment by roberthmiller** [comment]
https://github.com/cdr/sail/blob/bcf906366e626d48e9722319c3d50b5d8c48ec02/internal/editor/editor.go#L12

It already uses the EDITOR env var.
