### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by roberthmiller** [cdr/sail#240]
A makefile should be added to the repo in order to ensure that when installing the application, the user does not have to know all of the steps...

Something that I would find when helping people out is a `make install`.

Thoughts?

**Comment by deansheather** [comment]
Feel free to make a PR for one. The make step would just run `go build -o sail .` and the install step would copy it to `/usr/local/bin/sail`.

**Comment by roberthmiller** [comment]
Had a feeling that everything would be cool. Just thought to see what people thought before doing it.
